version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/blog
      SPRING_DATASOURCE_USERNAME: bloguser
      SPRING_DATASOURCE_PASSWORD: blogpass
    depends_on:
      - db
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: blogpass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  
  frontend:
    build:
      context: ./web/blog
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - app

volumes:
  db_data:
